spring.application.name=taskflow-backend
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

spring.flyway.enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}